"""add user role and advice table

Revision ID: c36f43844ca2
Revises: 
Create Date: 2025-01-16 16:43:42.182204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36f43844ca2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Créer d'abord les types enum
    userrole = sa.Enum('USER', 'BOTANIST', name='userrole')
    advicestatus = sa.Enum('PENDING', 'VALIDATED', 'REJECTED', name='advicestatus')
    
    userrole.create(op.get_bind(), checkfirst=True)
    advicestatus.create(op.get_bind(), checkfirst=True)
    
    # Supprimer l'ancienne table advices
    op.drop_table('advices')
    
    # Créer la nouvelle table advices
    op.create_table('advices',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('texte', sa.String(), nullable=False),
        sa.Column('status', advicestatus, nullable=False, server_default='PENDING'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('botanist_id', sa.Integer(), nullable=False),
        sa.Column('plant_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['botanist_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Ajouter le rôle aux utilisateurs
    op.add_column('users', sa.Column('role', userrole, nullable=False, server_default='USER'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_table('advices')
    
    # Recréer l'ancienne table advices
    op.create_table('advices',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('texte', sa.String(), nullable=False),
        sa.Column('date', sa.String(), nullable=False),
        sa.Column('botanist_id', sa.Integer(), nullable=False),
        sa.Column('plant_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['botanist_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Supprimer les types enum
    sa.Enum(name='userrole').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='advicestatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
